use std::{fs, io::Write, path::PathBuf};

use anyhow::Context;
use clap::Args;

use crate::utils::cargo;

#[derive(Debug, Args)]
pub struct HostArgs {
    #[arg(name = "path")]
    pub path: PathBuf,
}

pub fn handle_command(args: HostArgs) -> anyhow::Result<()> {
    let path = args.path;

    setup_crate(path)
}

fn setup_crate(host_path: PathBuf) -> anyhow::Result<()> {
    let host_str = host_path.to_str().context("path is not a valid UTF-8 string")?;

    let guest_path = host_path.join("src").join("guest");
    let guest_str = guest_path.to_str().unwrap();

    // run cargo to setup project
    cargo(None, ["new", host_str])?;
    cargo(
        Some(&host_path),
        [
            "add",
            "--git",
            "https://github.com/nexus-xyz/nexus-zkvm.git",
            "--branch",
            "simple-sdk",
            "nexus-sdk",
        ],
    )?;

    // src/main.rs
    fs::write(host_path.join("src/main.rs"), HOST_TEMPLATE_SRC_MAIN)?;
    fs::write(host_path.join("rust-toolchain.toml"), RUST_TOOLCHAIN)?;

    cargo(None, ["new", guest_str])?;
    cargo(
        Some(&guest_path),
        [
            "add",
            "--git",
            "https://github.com/nexus-xyz/nexus-zkvm.git",
            "nexus-rt",
        ],
    )?;

    // add postcard because it is used for (de)serializing from/to the input/output tapes
    cargo(
        Some(&guest_path),
        [
            "add",
            "postcard",
            "-F",
            "alloc",
        ],
    )?;

    let mut fp = fs::OpenOptions::new()
        .append(true)
        .open(guest_path.join("Cargo.toml"))?;

    writeln!(
        fp,
        concat!(
            "\n",
            "# Generated by nexus-tools, do not remove!\n",
            "#\n",
            "# This profile is used for generating proofs, as Nexus VM support for compiler optimizations is still under development.\n",
            "[profile.release-unoptimized]\n",
            "inherits = \"release\"\n",
            "opt-level = 0"
        )
    )?;

    // guest/.cargo/config.toml
    let guest_config_path = guest_path.join(".cargo");
    fs::create_dir_all(&guest_config_path)?;
    fs::write(guest_config_path.join("config.toml"), GUEST_TEMPLATE_CARGO_CONFIG)?;

    // guest/src/main.rs
    fs::write(guest_path.join("src/main.rs"), GUEST_TEMPLATE_SRC_MAIN)?;
    fs::write(guest_path.join("rust-toolchain.toml"), RUST_TOOLCHAIN)?;

    Ok(())
}

macro_rules! host_examples_dir {
    () => {
        concat!(env!("CARGO_MANIFEST_DIR"), "/../sdk/examples")
    };
}

macro_rules! guest_examples_dir {
    () => {
        concat!(env!("CARGO_MANIFEST_DIR"), "/../examples")
    };
}

const HOST_TEMPLATE_SRC_MAIN: &str = include_str!(concat!(host_examples_dir!(), "/nova_nobuild.rs"));

const GUEST_TEMPLATE_CARGO_CONFIG: &str = r#"[target.riscv32i-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tlink.x",
]
runner="nexus-run"
"#;
const GUEST_TEMPLATE_SRC_MAIN: &str = include_str!(concat!(guest_examples_dir!(), "/src/main.rs"));

// freeze toolchain that works with all provers
const RUST_TOOLCHAIN: &str = r#"[toolchain]
channel = "1.77.0"
targets = ["riscv32i-unknown-none-elf"]
"#;
