name: "Bug Report"
description: Report something that is broken or just not working as it should
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Before You Start...**

        This form is only for submitting bug reports. If you have a usage question
        or are unsure if this is really a bug, make sure to:

        - Read the [docs](https://github.com/nexus-xyz/nexus-zkvm)
        - Ask on [Telegram Chat](https://t.me/nexus_zkvm)
        - Ask on [Github Discussions](https://github.com/nexus-xyz/nexus-zkvm/discussions)

        Also try to search for your issue - it may have already been answered or even fixed in main or a development branch but not yet released.

        However, if you find that an old, closed issue still persists in the latest version, you should open a new issue using the form below instead of commenting on the old issue.
  - type: textarea
    id: program-info
    attributes:
      label: Program Information
      description: |
        Provide information about your zkVM program (i.e., your program that runs _inside_ the Nexus zkVM), ideally a minimal example to replicate the bug.
      placeholder: Program information
    validations:
      required: true
  - type: textarea
    id: project-info
    attributes:
      label: Project Information
      description: |
        Provide information about your project using the Nexus zkVM (i.e., your program that invokes the zkVM, if any), ideally a minimal example to replicate the bug.
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Reproduction Steps
      description: |
        What exactly is your application doing that causes the zkVM to malfunction?

        If we have to investigate the issue, what would we have to do to reproduce the issue?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is expected?
      description: |
        This can range from a textual explanation of what you were expecting to see/happen to providing the output of your program when run outside of/or in a different mode of the zkVM.
    validations:
      required: true
  - type: textarea
    id: actually-happening
    attributes:
      label: What is actually happening?
      description: |
        Explain what is happening that deviates from the expected output.
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: |
        Provide as much information about the environment you are using.
  - type: textarea
    id: additional-comments
    attributes:
      label: Any additional comments?
      description: e.g. some background/context of how you ran into this bug.
