[package]
name = "nexus-network"
edition.workspace = true
version.workspace = true
publish = false
default-run = "pcdnode"

[dependencies]
clap.workspace = true
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.18", features = [ "env-filter" ] }

async-channel = "1.9.0"
hyper = { version = "0.14", features = ["full"] }
fastwebsockets = { version = "0.4", features = ["upgrade"] }

reqwest = { version = "0.11.22", default-features = false, features = [ "blocking", "json" ] }

snmalloc-rs = { version = "0.3.4", optional = true }

serde.workspace = true
serde_json.workspace = true
postcard = { version = "1.0", features = ["use-std"] }
lz4 = "1.24"

sha2 = "0.10.8"

ark-ff.workspace = true
ark-ec.workspace = true
ark-serialize.workspace = true

nexus-riscv = { path = "../riscv" }
nexus-riscv-circuit = { path = "../riscv-circuit" }
nexus-prover = { path = "../prover" }
hex = "0.4.3"

[dev-dependencies]
nexus-riscv = { path = "../riscv" }

[features]
default = [ "snmalloc" ]
snmalloc = [ "snmalloc-rs" ]
