[package]
name = "supernova-benches"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.4.0"
ark-relations = { version = "0.4.0" }
ark-r1cs-std = { version = "0.4.0" }
ark-crypto-primitives = { version = "0.4.0", features = ["sponge"] }

ark-pallas = "0.4.0"
ark-vesta = "0.4.0"

criterion = "0.5"
pprof = { version = "0.13", features = ["criterion", "flamegraph"] }

supernova = { path = "..", default-features = false }

[features]
default = ["parallel"]
parallel = ["supernova/parallel"]

[[bench]]
name = "recursive-snark"
harness = false

[patch.crates-io]
ark-crypto-primitives = { git = "https://github.com/arkworks-rs/crypto-primitives", rev = "d27a5c8" }
ark-r1cs-std = { git = "https://github.com/arkworks-rs/r1cs-std/", rev = "2ca3bd7" }
ark-ff = { git = "https://github.com/arkworks-rs/algebra/", rev = "c92be0e" }
ark-ec = { git = "https://github.com/arkworks-rs/algebra/", rev = "c92be0e" }
ark-poly = { git = "https://github.com/arkworks-rs/algebra/", rev = "c92be0e" }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra/", rev = "c92be0e" }

ark-pallas = { git = "https://github.com/arkworks-rs/curves/", rev = "3fded1f" }
ark-vesta = { git = "https://github.com/arkworks-rs/curves/", rev = "3fded1f" }
