[package]
name = "nexus-profiler"
edition.workspace = true
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
[target.'cfg(unix)'.dependencies]
pprof = { version = "0.13", features = ["prost-codec", "frame-pointer"] }
