[package]
name = "nexus-vm-prover-air-column"
edition.workspace = true
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
nexus-vm-prover-air-column-derive = { path = "./air-column-derive" }
