use std::{fs, io::Write, path::PathBuf};

use anyhow::Context;
use clap::Args;

use crate::utils::cargo;

#[derive(Debug, Args)]
pub struct HostArgs {
    #[arg(name = "path")]
    pub path: PathBuf,
    #[arg(long, name = "rev", conflicts_with = "tag")]
    pub rev: Option<String>,
    #[arg(long, name = "tag", conflicts_with = "rev")]
    pub tag: Option<String>,
}

pub fn handle_command(args: HostArgs) -> anyhow::Result<()> {
    let path = args.path;
    let rev = args.rev;
    let mut tag = args.tag;

    if rev.is_none() && tag.is_none() {
        // default to current release
        tag = Some(String::from("0.3.4"));
    }

    setup_crate(path, rev, tag)
}

fn setup_crate(host_path: PathBuf, rev: Option<String>, tag: Option<String>) -> anyhow::Result<()> {
    assert!(rev.is_some() || tag.is_some());

    let host_str = host_path
        .to_str()
        .context("path is not a valid UTF-8 string")?;

    let guest_path = host_path.join("src").join("guest");
    let guest_str = guest_path.to_str().unwrap();

    let arg = if rev.is_some() { "--rev" } else { "--tag" };
    let ver = if let Some(v) = rev { v } else { tag.unwrap() };

    // run cargo to setup project
    cargo(None, ["new", host_str])?;
    cargo(
        Some(&host_path),
        [
            "add",
            "--git",
            "https://github.com/nexus-xyz/nexus-zkvm.git",
            arg,
            &ver,
            "nexus-sdk",
        ],
    )?;

    let mut fp1 = fs::OpenOptions::new()
        .append(true)
        .open(host_path.join("Cargo.toml"))?;

    writeln!(
        fp1,
        concat!(
            "\n",
            "[workspace]\n",
            "members = [\n",
            "    \"src/guest\"\n",
            "]\n\n",
        )
    )?;

    // src/main.rs
    fs::write(
        host_path.join("src/main.rs"),
        HOST_TEMPLATE_SRC_MAIN
            .replace(
                "const PACKAGE: &str = \"example\"",
                "const PACKAGE: &str = \"guest\"",
            )
            .replace(
                "const EXAMPLE: &str = \"example\"",
                "const EXAMPLE: &str = \"guest\"",
            ),
    )?;
    fs::write(host_path.join("rust-toolchain.toml"), RUST_TOOLCHAIN)?;

    cargo(None, ["new", guest_str])?;
    cargo(
        Some(&guest_path),
        [
            "add",
            "--git",
            "https://github.com/nexus-xyz/nexus-zkvm.git",
            arg,
            &ver,
            "nexus-rt",
        ],
    )?;

    // add postcard because it is used for (de)serializing from/to the input/output tapes
    cargo(
        Some(&guest_path),
        [
            "add",
            "postcard@1.1.1",
            "-F",
            "alloc",
            "--no-default-features",
        ],
    )?;

    let mut fp2 = fs::OpenOptions::new()
        .append(true)
        .open(guest_path.join("Cargo.toml"))?;

    writeln!(
        fp2,
        concat!(
            "\n",
            "# Generated by cargo-nexus, do not remove!\n",
            "#\n",
            "[features]\n",
            "cycles = [] # Enable cycle counting for run command\n",
        )
    )?;

    // guest/.cargo/config.toml
    let guest_config_path = guest_path.join(".cargo");
    fs::create_dir_all(&guest_config_path)?;
    fs::write(
        guest_config_path.join("config.toml"),
        GUEST_TEMPLATE_CARGO_CONFIG,
    )?;

    // guest/src/main.rs
    fs::write(guest_path.join("src/main.rs"), GUEST_TEMPLATE_SRC_MAIN)?;
    fs::write(guest_path.join("rust-toolchain.toml"), RUST_TOOLCHAIN)?;

    Ok(())
}

macro_rules! host_examples_dir {
    () => {
        concat!(env!("CARGO_MANIFEST_DIR"), "/../sdk/examples")
    };
}

macro_rules! guest_examples_dir {
    () => {
        concat!(env!("CARGO_MANIFEST_DIR"), "/../examples")
    };
}

const HOST_TEMPLATE_SRC_MAIN: &str = include_str!(concat!(host_examples_dir!(), "/stwo_build.rs"));

const GUEST_TEMPLATE_CARGO_CONFIG: &str = r#"[target.riscv32im-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tlink.x",
]
runner="nexus-run"
"#;
const GUEST_TEMPLATE_SRC_MAIN: &str = include_str!(concat!(guest_examples_dir!(), "/src/main.rs"));

// freeze toolchain that works with all provers
const RUST_TOOLCHAIN: &str = r#"[toolchain]
channel = "nightly-2025-04-06"
"#;
