[package]
name = "nexus-progress-bar"
edition.workspace = true
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1.0"
superconsole = "0.2"
