[package]
name = "nexus-tui"
edition.workspace = true
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1.0"
superconsole = { git = "https://github.com/facebookincubator/superconsole.git", rev = "8254a5c" }
